# Test build the arduino library with travis CI and PlatformIO
language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

matrix:
  fast_finish: true
  include:
    - env: BOARD=megaatmega2560
    - env: BOARD=due
    - env: BOARD=leonardo
    - env: BOARD=uno
  allow_failures:
    - env: BOARD=uno

install:
  - pip install -U platformio

script:
  - for e in examples/*; do
      platformio ci --board=$BOARD --lib=. $e/*;
    done
